/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminBooksRouteImport } from './routes/admin.books'
import { Route as AdminCirculationRouteImport } from './routes/admin.circulation'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as UserCatalogRouteImport } from './routes/user.catalog'
import { Route as UserHomeRouteImport } from './routes/user.home'
import { Route as UserLibraryRouteImport } from './routes/user.library'
import { Route as UserProfileRouteImport } from './routes/user.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCirculationRoute = AdminCirculationRouteImport.update({
  id: '/admin/circulation',
  path: '/admin/circulation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const UserCatalogRoute = UserCatalogRouteImport.update({
  id: '/user/catalog',
  path: '/user/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const UserHomeRoute = UserHomeRouteImport.update({
  id: '/user/home',
  path: '/user/home',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLibraryRoute = UserLibraryRouteImport.update({
  id: '/user/library',
  path: '/user/library',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/user/catalog': typeof UserCatalogRoute
  '/user/home': typeof UserHomeRoute
  '/user/library': typeof UserLibraryRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/user/catalog': typeof UserCatalogRoute
  '/user/home': typeof UserHomeRoute
  '/user/library': typeof UserLibraryRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/circulation': typeof AdminCirculationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/members': typeof AdminMembersRoute
  '/user/catalog': typeof UserCatalogRoute
  '/user/home': typeof UserHomeRoute
  '/user/library': typeof UserLibraryRoute
  '/user/profile': typeof UserProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/user/catalog'
    | '/user/home'
    | '/user/library'
    | '/user/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/user/catalog'
    | '/user/home'
    | '/user/library'
    | '/user/profile'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/books'
    | '/admin/circulation'
    | '/admin/dashboard'
    | '/admin/members'
    | '/user/catalog'
    | '/user/home'
    | '/user/library'
    | '/user/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminCirculationRoute: typeof AdminCirculationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMembersRoute: typeof AdminMembersRoute
  UserCatalogRoute: typeof UserCatalogRoute
  UserHomeRoute: typeof UserHomeRoute
  UserLibraryRoute: typeof UserLibraryRoute
  UserProfileRoute: typeof UserProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/circulation': {
      id: '/admin/circulation'
      path: '/admin/circulation'
      fullPath: '/admin/circulation'
      preLoaderRoute: typeof AdminCirculationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/catalog': {
      id: '/user/catalog'
      path: '/user/catalog'
      fullPath: '/user/catalog'
      preLoaderRoute: typeof UserCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/home': {
      id: '/user/home'
      path: '/user/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof UserHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/library': {
      id: '/user/library'
      path: '/user/library'
      fullPath: '/user/library'
      preLoaderRoute: typeof UserLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminCirculationRoute: AdminCirculationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMembersRoute: AdminMembersRoute,
  UserCatalogRoute: UserCatalogRoute,
  UserHomeRoute: UserHomeRoute,
  UserLibraryRoute: UserLibraryRoute,
  UserProfileRoute: UserProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
